name: 建置並部署 Spring Boot 應用程式

on:
  push:
    branches:
      - main  # 當 main 分支有提交時觸發流程

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: List files before chmod
        run: ls -la  # Add this step to list files

      - name: 設定 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 使 Maven Wrapper 可執行
        run: chmod +x mvnw
        working-directory: ./demo # 修改此行

      - name: 建置 Spring Boot 應用程式
        run: ./demo/mvnw clean package -DskipTests
        working-directory: ./demo

      - name: 建置 Docker 映像檔
        run: docker build -t ghcr.io/s980105211/my-spring-app:latest .

      - name: 登入 GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 將 Docker 映像檔推送到 GHCR
        run: docker push ghcr.io/s980105211/my-spring-app:latest

      - name: 登入 Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 部署到 Azure Container App
        run: |
          az containerapp update \
            --name my-spring-app \
            --resource-group my-resource-group \
            --image ghcr.io/s980105211/my-spring-app:latest
