name: Build and Deploy Spring Boot App
on:
push:
branches:
- main # 這表示當 "main" 分支有提交時觸發流程
jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2
- name: Set up JDK 17
uses: actions/setup-java@v1
with:
java-version: '17'
- name: Build Spring Boot app
run: ./mvnw clean package -DskipTests # 構建 Spring Boot 應用
- name: Build Docker image
run: docker build -t ghcr.io/s980105211/my-spring-app:latest . # 構建 Docker 映像
- name: Log in to GitHub Container Registry
run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
- name: Push Docker image to GHCR
run: docker push ghcr.io/s980105211/my-spring-app:latest
- name: Log in to Azure
uses: azure/login@v1
with:
creds: ${{ secrets.AZURE_CREDENTIALS }} # 用 Azure 賬戶的 credentials 登入
- name: Deploy to Azure Container App
run: |
az containerapp update \
--name my-spring-app \
--resource-group my-resource-group \
--image ghcr.io/<your-username>/my-spring-app:latest # 部署到 Azure Container App
